export const DATA = [
    {
        id: '1',
        name: 'Димний',
        bgimage: 'https://raw.githubusercontent.com/freshcode-training/ITCluster/main/dymnyi/dymnyi_bg.png',
        logo: 'https://raw.githubusercontent.com/freshcode-training/ITCluster/main/dymnyi/Dymnyj_logo_white.png',
        pageLogo: 'https://raw.githubusercontent.com/freshcode-training/ITCluster/main/dymnyi/Dymnyj_logo_white.png',
        animatedLogo: 'https://raw.githubusercontent.com/freshcode-training/ITCluster/main/dymnyi/dymnyi.gif',
        description: 'Відмінний кальян, широкий вибір алкоголю та закусок в центрі Запоріжжя',
        adress: 'Проспект Соборний, 166',
        phone: '+380 50 389 8998;',
        site: '@d.y.m.n.y.i',
        siteURL: 'http://instagram.com/d.y.m.n.y.i',
        adressURL: 'https://goo.gl/maps/T5ARhP3qGMVUKKoi8',
        discount: 'знижка 10%',
        bgColor: '#2E2F3A',
        textColor: '#ffffff',
    },
    {
        id: '2',
        name: 'Майстерня пончиків',
        bgimage: 'https://raw.githubusercontent.com/freshcode-training/ITCluster/main/majsternya_ponchykiv/majsternya-ponchykiv_bg.png',
        logo: 'https://raw.githubusercontent.com/freshcode-training/ITCluster/main/majsternya_ponchykiv/majsternya_ponchykiv_logo-black.png',
        pageLogo: 'https://raw.githubusercontent.com/freshcode-training/ITCluster/main/majsternya_ponchykiv/Majsternya_Ponchykiv_logo-white.png',
        animatedLogo: 'https://raw.githubusercontent.com/freshcode-training/ITCluster/main/majsternya_ponchykiv/donut.gif',
        description: 'Міні-пончики зі смаком дитинства. А також, морозиво, коктейлі, сендвічі та тортилья',
        adress: 'Бульвар Шевченка, 23',
        phone: '+380 97 723 1183',
        site: '@majsternya.ponchikiv',
        siteURL: 'https://www.instagram.com/majsternya.ponchikiv/',
        adressURL: 'https://www.google.com/maps/place//data=!4m2!3m1!1s0x40dc672a30125a05:0x582463d3eaa4010a?source=g.page.share',
        discount: 'знижка 10%',
        bgColor: '#2E3639',
        textColor: '#ffffff',
    },
    {
        id: '3',
        name: 'People',
        bgimage: 'https://raw.githubusercontent.com/freshcode-training/ITCluster/main/people/people_bg.png',
        logo: 'https://raw.githubusercontent.com/freshcode-training/ITCluster/main/people/people_logo.png',
        pageLogo: 'https://raw.githubusercontent.com/freshcode-training/ITCluster/main/people/people_cafe_logo_white.png',
        animatedLogo: 'https://raw.githubusercontent.com/freshcode-training/ITCluster/main/people/people.gif',
        description: 'Люди, напої та смачна їжа — все, що потрібно для гарного відпочинку',
        adress: 'Бульвар Шевченка, 18',
        phone: '+380 68 923 4543',
        site: '@people_cafe_zp',
        siteURL: 'https://instagram.com/people_cafe_zp',
        adressURL: 'https://goo.gl/maps/wYnMszGNHbFFRpyt6',
        discount: 'знижка 10%',
        bgColor: '#18181C',
        textColor: '#ffffff',
    },
    {
        id: '4',
        name: 'Капіталіст',
        bgimage: 'https://raw.githubusercontent.com/freshcode-training/ITCluster/main/kapitalist/kapitalist_bg.png',
        logo: 'https://raw.githubusercontent.com/freshcode-training/ITCluster/main/kapitalist/Kapitalist_logo_ua_black.png',
        pageLogo: 'https://raw.githubusercontent.com/freshcode-training/ITCluster/main/kapitalist/Kapitalist_logo_ua_white.png',
        animatedLogo: 'https://raw.githubusercontent.com/freshcode-training/ITCluster/main/kapitalist/kapitalist.gif',
        description: 'Розважальний центр з боулінгом та караоке. Знижка розповсюджується на кухню та оренду доріжок',
        adress: 'Проспект Соборний, 92',
        phone: '+380 50 484 0001',
        site: 'kapitalist.zp.ua',
        siteURL: 'http://kapitalist.zp.ua/',
        adressURL: 'https://www.google.com/maps/place//data=!4m2!3m1!1s0x40dc5e086e250fc5:0x49f4730a58330368?source=g.page.share',
        discount: 'знижка 10%',
        bgColor: '#87150B',
        textColor: '#ffffff',
    },
    {
        id: '5',
        name: 'Rock&Roll',
        bgimage: 'https://raw.githubusercontent.com/freshcode-training/ITCluster/main/rock%26roll/rock%26rock_background.png',
        logo: 'https://raw.githubusercontent.com/freshcode-training/ITCluster/main/rock%26roll/Rock%26Roll.png',
        pageLogo: 'https://raw.githubusercontent.com/freshcode-training/ITCluster/main/rock%26roll/Rock%26Roll.png',
        animatedLogo: 'https://raw.githubusercontent.com/freshcode-training/ITCluster/main/rock%26roll/rock.gif',
        adress: 'Вулиця Поштова, 141',
        phone: '+380 97 257 3377',
        site: 'rnr.com.ua',
        siteURL: 'https://rnr.com.ua/',
        adressURL: 'https://www.google.com/maps/place//data=!4m2!3m1!1s0x40dc6749e746d911:0x19927d17d03e62e3?source=g.page.share',
        description: 'Величезний вибір ролів, сетів, боулів, wok, та інших популярних страв азійської кухні',
        discount: 'знижка 10%',
        bgColor: '#FFCD00',
        textColor: '#000000',
    },
];